name: shift_jis
description: Shift_JIS Encoding and Decoding Library for Flutter.
version: 0.1.0
homepage: https://github.com/imamurh/shift_jis

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.imamurh.shift_jis
        pluginClass: ShiftJisPlugin
      ios:
        pluginClass: ShiftJisPlugin
